#!/usr/bin/env node
// Generate the service worker from the real build output.
//
// Runs after `vite build` (see package.json). It walks the emitted dist/ tree, keeps only the
// application shell — HTML, manifest, icons, hashed JS/CSS and the self-hosted fonts those
// stylesheets pull in — and writes a worker whose precache list is exactly those files. The
// cache name is a fingerprint over the *contents* of every shell file, so an in-place asset
// edit still busts the cache.
//
// Deliberate constraints:
//   - install is atomic (`cache.addAll`): a half-filled shell never becomes active.
//   - the fetch handler never calls `cache.put`, so no CDN media or arbitrary response can
//     enter the cache; non-shell requests are left to the network.
//   - activation deletes only caches this app created (its own name prefix).

import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const dist = join(root, 'dist')

if (!existsSync(join(dist, 'index.html'))) {
  console.error('build-sw: dist/index.html not found — run `vite build` first')
  process.exit(1)
}

const walk = dir => {
  const out = []
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else out.push(p)
  }
  return out
}

const urlPath = abs => '/' + relative(dist, abs).split(/[\\/]/).join('/')

const assets = []
for (const abs of walk(dist)) {
  const rel = urlPath(abs)
  if (rel === '/sw.js') continue
  if (/\.(?:js|css|woff2|png|svg|json|html|webmanifest|ico)$/.test(rel)) assets.push(abs)
}

// The self-hosted fonts are referenced from inside the built stylesheet, not from index.html.
const cssFiles = assets.filter(a => a.endsWith('.css'))
for (const css of cssFiles) {
  const text = readFileSync(css, 'utf8')
  for (const m of text.matchAll(/url\((['"]?)([^'")]+\.woff2)\1\)/g)) {
    const raw = m[2]
    if (/^https?:|^\/\//.test(raw)) continue
    const abs = resolve(join(css, '..'), raw.startsWith('/') ? '.' + raw : raw)
    if (existsSync(abs) && !assets.includes(abs)) assets.push(abs)
  }
}

if (!assets.some(a => a.endsWith('index.html'))) {
  console.error('build-sw: no index.html in the shell asset list')
  process.exit(1)
}

// Fingerprint over contents, sorted by URL path so the hash does not depend on directory order.
const shellUrls = [...new Set(assets.map(urlPath))].sort()
const hash = createHash('sha256')
for (const url of shellUrls) {
  const abs = join(dist, url.replace(/^\//, ''))
  hash.update(url).update('\0').update(readFileSync(abs))
}
const stamp = hash.digest('hex').slice(0, 12)
const cacheName = `workout-index-${stamp}`

const sw = `/* Generated by scripts/build-sw.mjs — do not edit. Build ${stamp}. */
const CACHE = ${JSON.stringify(cacheName)}
const SHELL = ${JSON.stringify(shellUrls, null, 2)}
const SHELL_SET = new Set(SHELL)

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(SHELL))
      .then(() => self.skipWaiting())
      .catch(() => { /* keep the previous worker serving */ })
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('workout-index-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
      // Never reload the page on update: the new cache takes effect on the next visit and any
      // in-flight user state survives.
  )
})

self.addEventListener('fetch', event => {
  const request = event.request
  if (request.method !== 'GET') return
  let url
  try { url = new URL(request.url) } catch { return }
  // Exercise media lives on a CDN and is deliberately never cached here.
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    // SPA shell for every route, online first, cached shell when the network is gone.
    event.respondWith(fetch(request).catch(() => caches.match('/index.html')))
    return
  }

  if (!SHELL_SET.has(url.pathname)) return // unknown paths: network only, nothing cached
  event.respondWith(caches.match(url.pathname).then(hit => hit || fetch(request)))
})
`

writeFileSync(join(dist, 'sw.js'), sw)
console.log(`build-sw: cache ${cacheName}, ${shellUrls.length} shell files`)
